/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 JsIcon.gltf 
Author: agustin.trezza (https://sketchfab.com/agustin.trezza)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/javascript-1-e6a5af39d2b3495fb4fb1f8f94d3efda
Title: Javascript (1)
*/

//JAVASCRIPT ICON DID NOT GET USED IN FINAL VERSION
//JAVASCRIPT ICON DID NOT GET USED IN FINAL VERSION
//JAVASCRIPT ICON DID NOT GET USED IN FINAL VERSION

import React, { useState } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/JsIcon.gltf')
  const [ rotation, setRotation ] = useState(0) 
  const [targetRotation, setTargetRotation] = useState(0)

  const handleClick = () => {
    setTargetRotation((prev) => prev + (Math.PI*2) )  
  }

  useFrame(() => {
    setRotation((current) => {
      const speed = 0.1  
      if (Math.abs(targetRotation - current) < 0.01) return targetRotation 
      return current + (targetRotation - current) * speed  
    })
  })

  return (
    <group {...props} dispose={null} scale={0.15} onClick={handleClick}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.mat_3220964} rotation={[-Math.PI , Math.PI, -(Math.PI / 2) + (-rotation)]} />
    </group>
  )
}

useGLTF.preload('/JsIcon.gltf')
