/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 reactIcon.gltf 
Author: xenadus (https://sketchfab.com/xenadus)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/react-logo-76174ceeba96487f9863f974636f641e
Title: React logo
*/



import React, { useState } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/reactIcon.gltf')
  const [spinY, setSpinY] = useState(0)
  const [targetRotation, setTargetRotation] = useState(0)

  const handleClick = () => {
    setTargetRotation((prev) => prev + (Math.PI*2) )  
  }

  useFrame(() => {
    setSpinY((current) => {
      const speed = 0.05  
      if (Math.abs(targetRotation - current) < 0.01) return targetRotation 
      return current + (targetRotation - current) * speed  
    })
  })

  const screenHeight = window.innerHeight;
  const screenWidth = window.innerWidth;

  let userScale = screenHeight * screenWidth;

  userScale = Math.sqrt(userScale)

  userScale = userScale/14

  //set size of scale to 0.0085 rather than 0.001, as the latter seemed a bit too big

  return (
    <group {...props} dispose={null} onClick={handleClick}>
      <group scale={0.0085}>  
        <mesh
          geometry={nodes['React-Logo_Material002_0'].geometry}
          material={materials['Material.002']}
          position={[0, 7.935, 18.102]}
          rotation={[6/2, 0.5+spinY*2, -(spinY*1)]}  //1 2 3 || // 0 0 spinY // up+down / left+right / rotate
          scale={[userScale/2, userScale/2, userScale/2]}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/reactIcon.gltf')